# Generated by Django 5.1.7 on 2025-03-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(default=None),
        ),
    ]
